languageCode = "en-us"
title = "NVIDIA Networking Documentation"
theme = "netDocs"
baseURL = "/"
relURLs = true
googleAnalytics = "G-HTM5Y02305"
#Book configuration
disablePathToLower = true
enableGitInfo= true
noChmod = true
enableRobotsTXT = true
disableKinds = ["RSS", "taxonomy", "term"]

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 1
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.subnav]]
    identifier = "cumulus-linux"
    title = "NVIDIA Cumulus Linux"
    url = "/cumulus-linux-43/"
    weight = 10

  [[menu.subnav]]
    identifier = "cumulus-netq"
    title = "NVIDIA NetQ"
    url = "/cumulus-netq-33/"
    weight = 20

  [[menu.subnav]]
    identifier = "cumulus-vx"
    title = "NVIDIA Cumulus VX"
    url = "/cumulus-vx/"
    weight = 30

  [[menu.subnav]]
    identifier = "sonic-202012"
    title = "SONiC"
    url = "/sonic-202012/"
    weight = 40

  [[menu.dropnav]]
    identifier = "cumulus-rmp"
    title = "Cumulus RMP"
    url = "/cumulus-rmp/"
    weight = 10

[Params]
#Syntax Highlighting
pygmentsCodeFencesGuessSyntax = true
pygmentsUseClasses = true

showVisitedLinks = true

# (Optional, default true) Show or hide table of contents globally
  # You can also specify this parameter per page in front matter
  BookShowToC= true

  # (Optional, default none) Set leaf bundle to render as side menu
  # When not specified file structure and weights will be used
  #BookMenuBundle= /menus

  # Set menu to render from Current top level section(product)
  BookCurrentSectionMenu = true

  # (Optional, default docs) Specify section of content to render as menu
  # You can also set value to "*" to render all sections to menu
  #BookSection = "CumulusLinux"

  # This value is duplicate of $link-color for making active link highlight in menu bundle mode
  # BookMenuBundleActiveLinkColor: \#004ed0

  # Include JS scripts in pages. Disabled by default.
  # - Keep side menu on same scroll position during navigation
  BookEnableJS= true

  # Set source repository location.
  # Used for 'Last Modified' and 'Edit this page' links.
  BookRepo = "https://github.com/CumulusNetworks/docs"

  # Enable "Edit this page" links for 'doc' page type.
  # Disabled by default. Uncomment to enable. Requires 'BookRepo' param.
  # Path must point to 'content' directory of repo.
  BookEditPath = "edit/stage/content"

  # Configure the date format used on the pages
  # - In git information
  # - In blog posts
  BookDateFormat= "Jan 2, 2006"

