version: "4.0"

documents:
  # Item tag below is not of any significance, purely for structure
  cumulus-linux:
    # PDF file name
    name: Cumulus-Linux-User-Guide
    # Path to the index HTML file for the title page
    title-page: cumulus-linux/title/
    # Paths to index files to include
    folders:
      - cumulus-linux/
      - cumulus-linux/Quick-Start-Guide
      - cumulus-linux/Installation-Management
      - cumulus-linux/Installation-Management/Managing-Cumulus-Linux-Disk-Images
      - cumulus-linux/Installation-Management/Installing-a-New-Cumulus-Linux-Image
      - cumulus-linux/Installation-Management/Upgrading-Cumulus-Linux
      - cumulus-linux/Installation-Management/Migrating-from-LNV-to-EVPN
      - cumulus-linux/Installation-Management/Back-up-and-Restore
      - cumulus-linux/Installation-Management/Adding-and-Updating-Packages
      - cumulus-linux/Installation-Management/Zero-Touch-Provisioning-ZTP
      - cumulus-linux/System-Configuration
      - cumulus-linux/System-Configuration/Authentication,-Authorization-and-Accounting
      - cumulus-linux/System-Configuration/Authentication,-Authorization-and-Accounting/SSH-for-Remote-Access
      - cumulus-linux/System-Configuration/Authentication,-Authorization-and-Accounting/User-Accounts
      - cumulus-linux/System-Configuration/Authentication,-Authorization-and-Accounting/Using-sudo-to-Delegate-Privileges
      - cumulus-linux/System-Configuration/Authentication,-Authorization-and-Accounting/LDAP-Authentication-and-Authorization
      - cumulus-linux/System-Configuration/Authentication,-Authorization-and-Accounting/TACACS+
      - cumulus-linux/System-Configuration/Authentication,-Authorization-and-Accounting/RADIUS-AAA
      - cumulus-linux/System-Configuration/Netfilter-ACLs
      - cumulus-linux/System-Configuration/Netfilter-ACLs/Default-Cumulus-Linux-ACL-Configuration
      - cumulus-linux/System-Configuration/Netfilter-ACLs/Filtering-Learned-MAC-Addresses
      - cumulus-linux/System-Configuration/Network-Command-Line-Utility-NCLU
      - cumulus-linux/System-Configuration/Setting-Date-and-Time
      - cumulus-linux/System-Configuration/Services-and-Daemons-in-Cumulus-Linux
      - cumulus-linux/System-Configuration/Configuring-switchd
      - cumulus-linux/System-Configuration/Power-over-Ethernet-PoE
      - cumulus-linux/System-Configuration/Configuring-a-Global-Proxy
      - cumulus-linux/System-Configuration/HTTP-API
      - cumulus-linux/Layer-1-and-Switch-Ports
      - cumulus-linux/Layer-1-and-Switch-Ports/Interface-Configuration-and-Management
      - cumulus-linux/Layer-1-and-Switch-Ports/Interface-Configuration-and-Management/Switch-Port-Attributes
      - cumulus-linux/Layer-1-and-Switch-Ports/Interface-Configuration-and-Management/ifplugd
      - cumulus-linux/Layer-1-and-Switch-Ports/Buffer-and-Queue-Management
      - cumulus-linux/Layer-1-and-Switch-Ports/Buffer-and-Queue-Management/Hardware-enabled-DDOS-Protection
      - cumulus-linux/Layer-1-and-Switch-Ports/DHCP-Relays
      - cumulus-linux/Layer-1-and-Switch-Ports/DHCP-Servers
      - cumulus-linux/Layer-1-and-Switch-Ports/802.1X-Interfaces
      - cumulus-linux/Layer-1-and-Switch-Ports/Prescriptive-Topology-Manager-PTM
      - cumulus-linux/Layer-1-and-Switch-Ports/Port-Security
      - cumulus-linux/Layer-2
      - cumulus-linux/Layer-2/Link-Layer-Discovery-Protocol
      - cumulus-linux/Layer-2/Link-Layer-Discovery-Protocol/Voice-VLAN
      - cumulus-linux/Layer-2/Ethernet-Bridging-VLANs
      - cumulus-linux/Layer-2/Ethernet-Bridging-VLANs/VLAN-aware-Bridge-Mode
      - cumulus-linux/Layer-2/Ethernet-Bridging-VLANs/Traditional-Bridge-Mode
      - cumulus-linux/Layer-2/Ethernet-Bridging-VLANs/VLAN-Tagging
      - cumulus-linux/Layer-2/Spanning-Tree-and-Rapid-Spanning-Tree
      - cumulus-linux/Layer-2/Bonding-Link-Aggregation
      - cumulus-linux/Layer-2/Multi-Chassis-Link-Aggregation-MLAG
      - cumulus-linux/Layer-2/LACP-Bypass
      - cumulus-linux/Layer-2/Virtual-Router-Redundancy-VRR-and-VRRP
      - cumulus-linux/Layer-2/IGMP-and-MLD-Snooping
      - cumulus-linux/Network-Virtualization
      - cumulus-linux/Network-Virtualization/Ethernet-Virtual-Private-Network-EVPN
      - cumulus-linux/Network-Virtualization/Ethernet-Virtual-Private-Network-EVPN/Basic-Configuration
      - cumulus-linux/Network-Virtualization/Ethernet-Virtual-Private-Network-EVPN/EVPN-Enhancements
      - cumulus-linux/Network-Virtualization/Ethernet-Virtual-Private-Network-EVPN/Inter-subnet-Routing
      - cumulus-linux/Network-Virtualization/Ethernet-Virtual-Private-Network-EVPN/EVPN-PIM
      - cumulus-linux/Network-Virtualization/Ethernet-Virtual-Private-Network-EVPN/Configuration-Examples
      - cumulus-linux/Network-Virtualization/Ethernet-Virtual-Private-Network-EVPN/Troubleshooting
      - cumulus-linux/Network-Virtualization/Virtualization-Integrations
      - cumulus-linux/Network-Virtualization/Virtualization-Integrations/Integrating-Hardware-VTEPs-with-Midokura-MidoNet-and-OpenStack
      - cumulus-linux/Network-Virtualization/Virtualization-Integrations/Integrating-Hardware-VTEPs-with-VMware-NSX-V
      - cumulus-linux/Network-Virtualization/Virtualization-Integrations/Integrating-Hardware-VTEPs-with-VMware-NSX-MH
      - cumulus-linux/Network-Virtualization/Virtualization-Integrations/OVSDB-Server-High-Availability
      - cumulus-linux/Network-Virtualization/VXLAN-Active-Active-Mode
      - cumulus-linux/Network-Virtualization/VXLAN-Routing
      - cumulus-linux/Network-Virtualization/Static-VXLAN-Tunnels
      - cumulus-linux/Network-Virtualization/VXLAN-Scale
      - cumulus-linux/Network-Virtualization/Hybrid-Cloud-Connectivity-with-QinQ-and-VXLANs
      - cumulus-linux/Layer-3
      - cumulus-linux/Layer-3/FRRouting-Overview
      - cumulus-linux/Layer-3/Configuring-FRRouting
      - cumulus-linux/Layer-3/Configuring-FRRouting/Comparing-NCLU-and-vtysh-Commands
      - cumulus-linux/Layer-3/Routing
      - cumulus-linux/Layer-3/Introduction-to-Routing-Protocols
      - cumulus-linux/Layer-3/Network-Topology
      - cumulus-linux/Layer-3/Address-Resolution-Protocol-ARP
      - cumulus-linux/Layer-3/Open-Shortest-Path-First-OSPF
      - cumulus-linux/Layer-3/Open-Shortest-Path-First-v3-OSPFv3
      - cumulus-linux/Layer-3/Border-Gateway-Protocol-BGP
      - cumulus-linux/Layer-3/Policy-based-Routing
      - cumulus-linux/Layer-3/Bidirectional-Forwarding-Detection-BFD
      - cumulus-linux/Layer-3/Equal-Cost-Multipath-Load-Sharing-Hardware-ECMP
      - cumulus-linux/Layer-3/Redistribute-Neighbor
      - cumulus-linux/Layer-3/Virtual-Routing-and-Forwarding-VRF
      - cumulus-linux/Layer-3/Management-VRF
      - cumulus-linux/Layer-3/GRE-Tunneling
      - cumulus-linux/Layer-3/Protocol-Independent-Multicast-PIM
      - cumulus-linux/Layer-3/Segment-Routing
      - cumulus-linux/Monitoring-and-Troubleshooting
      - cumulus-linux/Monitoring-and-Troubleshooting/Monitoring-System-Hardware
      - cumulus-linux/Monitoring-and-Troubleshooting/Monitoring-System-Hardware/Network-Switch-Port-LED-and-Status-LED-Guidelines
      - cumulus-linux/Monitoring-and-Troubleshooting/Monitoring-System-Hardware/TDR-Cable-Diagnostics
      - cumulus-linux/Monitoring-and-Troubleshooting/Understanding-the-cl-support-Output-File
      - cumulus-linux/Monitoring-and-Troubleshooting/Understanding-the-cl-support-Output-File/Troubleshooting-Log-Files
      - cumulus-linux/Monitoring-and-Troubleshooting/Understanding-the-cl-support-Output-File/Troubleshooting-the-etc-Directory
      - cumulus-linux/Monitoring-and-Troubleshooting/Troubleshooting-Network-Interfaces
      - cumulus-linux/Monitoring-and-Troubleshooting/Troubleshooting-Network-Interfaces/Monitoring-Interfaces-and-Transceivers-Using-ethtool
      - cumulus-linux/Monitoring-and-Troubleshooting/Network-Troubleshooting
      - cumulus-linux/Monitoring-and-Troubleshooting/Network-Troubleshooting/Using-NCLU-to-Troubleshoot-Your-Network-Configuration
      - cumulus-linux/Monitoring-and-Troubleshooting/Network-Troubleshooting/Mellanox-WJH
      - cumulus-linux/Monitoring-and-Troubleshooting/Network-Troubleshooting/Monitoring-System-Statistics-and-Network-Traffic-with-sFlow
      - cumulus-linux/Monitoring-and-Troubleshooting/Simple-Network-Management-Protocol-SNMP
      - cumulus-linux/Monitoring-and-Troubleshooting/Simple-Network-Management-Protocol-SNMP/Using-Nutanix-Prism-as-a-Monitoring-Tool
      - cumulus-linux/Monitoring-and-Troubleshooting/Single-User-Mode-Password-Recovery
      - cumulus-linux/Monitoring-and-Troubleshooting/Resource-Diagnostics-Using-cl-resource-query
      - cumulus-linux/Monitoring-and-Troubleshooting/Monitoring-Virtual-Device-Counters
      - cumulus-linux/Monitoring-and-Troubleshooting/ASIC-Monitoring
      - cumulus-linux/Monitoring-and-Troubleshooting/Monitoring-Best-Practices
      - cumulus-linux/Monitoring-and-Troubleshooting/switchd-Log-Message-Reference
      - cumulus-linux/Monitoring-and-Troubleshooting/FRRouting-Log-Message-Reference
      - cumulus-linux/Network-Solutions
      - cumulus-linux/Network-Solutions/Data-Center-Host-to-ToR-Architecture
      - cumulus-linux/Network-Solutions/Cumulus-Networks-Services-Demos
      - cumulus-linux/Network-Solutions/Campus
      - cumulus-linux/Network-Solutions/Docker-on-Cumulus-Linux
      - cumulus-linux/Network-Solutions/OpenStack-Neutron-ML2-and-Cumulus-Linux
      - cumulus-linux/Network-Solutions/Anycast-Design-Guide
      - cumulus-linux/Network-Solutions/RDMA-over-Converged-Ethernet-RoCE
      - cumulus-linux/Network-Solutions/Cumulus-Hyperconverged-Solution-with-Nutanix
