name: 'Release Note Publisher'

on:
  push:
    branches:
      - rn-stage

jobs:
  release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Run the **STAGE** RN script
        run: |
          python3 utils/build_rnstage_rns.py
## comment out FOSS processing temporarily for rn-stage !!          python3 utils/build_rnstage_foss_licenses.py
      - name: Create PR
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "Automated release note commit"

    env:
      GITHUB_TOKEN: ${{ secrets.STU_GITHUB_TOKEN }}
